# Generated by Django 2.2.11 on 2023-06-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('Ferrari', 'fr'), ('Honda', 'hn'), ('Boujie', 'bo'), ('Suzuki', 'sz'), ('Toyota', 'ty')], default=None, max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(choices=[('Red', 'rd'), ('Yellow', 'yw'), ('Blue', 'bl'), ('Green', 'grn')], default=None, max_length=50)),
                ('position', models.FloatField(max_length=50)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
