# Generated by Django 2.2.11 on 2023-06-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.FloatField(default=None, max_length=50),
        ),
    ]
