# Generated by Django 2.2.11 on 2023-06-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_auto_20230611_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
