# Generated by Django 2.2.11 on 2023-06-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_auto_20230611_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.FloatField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
