# Generated by Django 2.2.11 on 2023-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_auto_20230611_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.FloatField(max_length=50),
        ),
    ]
